    # .github/workflows/python-tests.yml
    name: Python CI Tests 

    on:
      push:
        branches:
          - main 
      pull_request:
        branches:
          - main 

    jobs:
      build: 
        runs-on: ubuntu-latest 

        steps:
        - uses: actions/checkout@v4 
          with:
            fetch-depth: 0 

        - name: Set up Python
          uses: actions/setup-python@v5 
          with:
            python-version: '3.13'
            cache: 'pip' 

        - name: Install dependencies 
          run: | 
            python -m pip install --upgrade pip # Garante que o pip esteja atualizado
            pip install -r requirements.txt # Instala todas as bibliotecas listadas no requirements.txt

        - name: Run tests with pytest 
          run: |
            pytest tests/ # Roda o pytest na pasta 'tests'
    